#!bin/sh
function about() {
cat <<EOF
#####################################
# The Ultimate Bashrc File			#
# .bashrc					        #
# Creator: yuwillsee		        #
# Version: 1.0			 		    #
# Ressources in shell				#
#####################################
EOF
}