#!/bin/zsh
set -e

function show_help() {
    cat << EOF
Usage: ${0##*/}
    [-h show help]
    [-d distribution ]
                            debian
                            ubuntu *
                            archlinux
    [-e environment ]
                            internal
                            external *

Installing scripts for eburo linux

    -d                      Linux distribution cibled
    -e                      Environment that PC is in
    -h                      display this help and exit

EOF
    exit $1
}

if [[ $# -eq 0 ]] ; then
    show_help 0
fi

distribution=ubuntu
environment=external

while getopts hs:i: opt; do
    case $opt in
        h)
            show_help 0
        ;;
        d)
            distribution="$OPTARG"
        ;;
        e)
            environment="$OPTARG"
        ;;
        *)
            show_help 1 >&2
        ;;
    esac
done

shift "$((OPTIND-1))"
if (($# > 0)); then
    echo "unexpected argument(s): $@"
    show_help 1 >&2
fi

export SCRIPTS_DIR="$(dirname "$0")/scripts"
${SCRIPTS_DIR}/setup.sh $distribution $environment
