#!bin/zsh

export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"
export LC_ALL=en_US.UTF-8
plugins=(git history-substring-search themes vagrant docker docker-compose z)
source $ZSH/oh-my-zsh.sh

alias vi='vim'
alias zshreload="source ~/.zshrc"
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

#dockers
alias dockercontainerclean='docker rm $(docker ps -qa --no-trunc --filter "status=exited")'
alias dockerimageclean='docker images --filter dangling=true -q | xargs docker rmi'
alias sshagent="eval $(ssh-agent -s)"

export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
export PATH=$HOME/.npm-packages/bin:$PATH
export CHROME_BIN=/usr/bin/chromium-browser
export CHROME_PATH=/usr/lib/chromium

echo ""
neofetch
echo ""